-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hayai_consensus_core]: type definitions
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace HayaiCore

/-- [hayai_consensus_core::block_limits::BlockLimits]
    Source: 'crates/hayai-consensus-core/src/block_limits.rs', lines 6:0-19:1
    Visibility: public -/
structure block_limits.BlockLimits where
  sigops : Std.U32
  orchard_actions : Std.U32
  ironwood_actions : Std.U32
  sapling_ios : Std.U32
  shielded_cost : Std.U32

/-- [hayai_consensus_core::chain_spec::Upgrade]
    Source: 'crates/hayai-consensus-core/src/chain_spec.rs', lines 20:0-33:1
    Visibility: public -/
@[discriminant isize]
inductive chain_spec.Upgrade where
| Sprout : chain_spec.Upgrade
| Overwinter : chain_spec.Upgrade
| Sapling : chain_spec.Upgrade
| Blossom : chain_spec.Upgrade
| Heartwood : chain_spec.Upgrade
| Canopy : chain_spec.Upgrade
| Nu5 : chain_spec.Upgrade
| Nu6 : chain_spec.Upgrade
| Nu6_1 : chain_spec.Upgrade
| Nu6_2 : chain_spec.Upgrade
| Nu6_3 : chain_spec.Upgrade
| Nu7 : chain_spec.Upgrade

/-- [hayai_consensus_core::ConsensusError]
    Source: 'crates/hayai-consensus-core/src/lib.rs', lines 91:0-137:1
    Visibility: public -/
@[discriminant isize]
inductive ConsensusError where
| UnsupportedUpgrade : chain_spec.Upgrade → Std.U32 → ConsensusError
| NoRuleSet : chain_spec.Upgrade → ConsensusError
| UnknownBranch : Std.U32 → ConsensusError
| IssuedSupplyUnknown : Std.U32 → ConsensusError
| NegativeNsmBalance : Std.U32 → Std.U128 → Std.U64 → ConsensusError
| NoLockboxDisbursement : Std.U32 → ConsensusError
| NsmSeedMismatch : Std.U64 → Std.U64 → ConsensusError
| MoneyOverflow : ConsensusError
| Overflow : ConsensusError
| DivisionByZero : ConsensusError
| UncheckedSpec : ConsensusError

/-- [hayai_consensus_core::lockbox::Disbursement]
    Source: 'crates/hayai-consensus-core/src/lockbox.rs', lines 16:0-23:1
    Visibility: public -/
structure lockbox.Disbursement where
  count : Std.Usize
  value : Std.U64
  script : Array Std.U8 23#usize

/-- [hayai_consensus_core::funding::Receiver]
    Source: 'crates/hayai-consensus-core/src/funding.rs', lines 23:0-32:1
    Visibility: public -/
@[discriminant isize]
inductive funding.Receiver where
| Ecc : funding.Receiver
| ZcashFoundation : funding.Receiver
| MajorGrants : funding.Receiver
| Deferred : funding.Receiver

/-- [hayai_consensus_core::funding::Stream]
    Source: 'crates/hayai-consensus-core/src/funding.rs', lines 55:0-65:1
    Visibility: public -/
structure funding.Stream where
  receiver : funding.Receiver
  numerator : Std.U64
  scripts : alloc.vec.Vec (Array Std.U8 23#usize)

/-- [hayai_consensus_core::funding::StreamSet]
    Source: 'crates/hayai-consensus-core/src/funding.rs', lines 69:0-78:1
    Visibility: public -/
structure funding.StreamSet where
  start : Std.U32
  «end» : Std.U32
  ends_at_third_halving : Bool
  streams : alloc.vec.Vec funding.Stream

/-- [hayai_consensus_core::chain_spec::CoreSpec]
    Source: 'crates/hayai-consensus-core/src/chain_spec.rs', lines 108:0-158:1
    Visibility: public -/
structure chain_spec.CoreSpec where
  activation_heights : Array (Option Std.U32) 12#usize
  slow_start_interval : Std.U32
  pre_blossom_halving_interval : Std.U32
  pow_limit : Array Std.U8 32#usize
  pow_limit_bits : Std.U32
  disable_pow : Bool
  min_difficulty_start_height : Option Std.U32
  max_time_start_height : Std.U32
  orchard_disabled_start_height : Option Std.U32
  coinbase_must_be_shielded : Bool
  funding_streams : alloc.vec.Vec funding.StreamSet
  lockbox_disbursements : alloc.vec.Vec lockbox.Disbursement
  founders_scripts : alloc.vec.Vec (Array Std.U8 23#usize)
  nsm_seed : Option Std.U64
  test_reissuance_height : Option Std.U32
  first_halving : Option Std.U32

/-- [hayai_consensus_core::chain_spec::SpecError]
    Source: 'crates/hayai-consensus-core/src/chain_spec.rs', lines 162:0-206:1
    Visibility: public -/
@[discriminant isize]
inductive chain_spec.SpecError where
| Sprout : chain_spec.SpecError
| Order : chain_spec.Upgrade → Std.U32 → chain_spec.SpecError
| HalvingInterval : Std.U32 → chain_spec.SpecError
| SlowStart : Std.U32 → chain_spec.SpecError
| NoFirstHalving : chain_spec.SpecError
| StreamEnd : Std.U32 → chain_spec.SpecError
| StreamRange : Std.U32 → Std.U32 → chain_spec.SpecError
| StreamReceiver : funding.Receiver → chain_spec.SpecError
| StreamNumerators : Std.U128 → chain_spec.SpecError
| DeferredScript : chain_spec.SpecError
| StreamScripts :
  funding.Receiver →
  Std.U32 →
  Std.U32 →
  Std.Usize →
  Std.Usize →
  chain_spec.SpecError
| DisbursementAmount : chain_spec.SpecError
| OrchardSoftFork : Std.U32 → chain_spec.SpecError
| Rule : ConsensusError → chain_spec.SpecError

/-- [hayai_consensus_core::funding::address_period::{closure}]
    Source: 'crates/hayai-consensus-core/src/funding.rs', lines 294:8-294:88 -/
def funding.address_period.closure := Std.U32 × Std.U32

/-- [hayai_consensus_core::coinbase_value::OutputKind]
    Source: 'crates/hayai-consensus-core/src/coinbase_value.rs', lines 25:0-29:1
    Visibility: public -/
@[discriminant isize]
inductive coinbase_value.OutputKind where
| FoundersReward : coinbase_value.OutputKind
| FundingStream : funding.Receiver → coinbase_value.OutputKind
| LockboxDisbursement : coinbase_value.OutputKind

/-- [hayai_consensus_core::coinbase_value::RequiredOutput]
    Source: 'crates/hayai-consensus-core/src/coinbase_value.rs', lines 33:0-39:1
    Visibility: public -/
structure coinbase_value.RequiredOutput where
  kind : coinbase_value.OutputKind
  value : Std.U64
  script : Array Std.U8 23#usize

/-- [hayai_consensus_core::coinbase_value::CoinbaseOutput]
    Source: 'crates/hayai-consensus-core/src/coinbase_value.rs', lines 43:0-48:1
    Visibility: public -/
structure coinbase_value.CoinbaseOutput where
  value : Std.U64
  script : alloc.vec.Vec Std.U8

/-- [hayai_consensus_core::coinbase_value::ShieldedBalances]
    Source: 'crates/hayai-consensus-core/src/coinbase_value.rs', lines 54:0-58:1
    Visibility: public -/
structure coinbase_value.ShieldedBalances where
  sapling : Std.I64
  orchard : Std.I64
  ironwood : Std.I64

/-- [hayai_consensus_core::coinbase_value::CoinbaseError]
    Source: 'crates/hayai-consensus-core/src/coinbase_value.rs', lines 61:0-99:1
    Visibility: public -/
@[discriminant isize]
inductive coinbase_value.CoinbaseError where
| Consensus : ConsensusError → coinbase_value.CoinbaseError
| MissingOutput :
  coinbase_value.OutputKind →
  Std.U64 →
  alloc.vec.Vec Std.U8 →
  coinbase_value.CoinbaseError
| WrongAmount :
  coinbase_value.OutputKind →
  Std.U64 →
  Std.U64 →
  coinbase_value.CoinbaseError
| WrongScript :
  coinbase_value.OutputKind →
  Std.U64 →
  alloc.vec.Vec Std.U8 →
  alloc.vec.Vec Std.U8 →
  coinbase_value.CoinbaseError
| ValueAboveLimit : Std.I128 → Std.I128 → coinbase_value.CoinbaseError
| ValueNotExact : Std.I128 → Std.I128 → coinbase_value.CoinbaseError
| NegativeDeferredPool : Std.U64 → Std.U64 → coinbase_value.CoinbaseError

/-- [hayai_consensus_core::subsidy_schedule::Subsidy]
    Source: 'crates/hayai-consensus-core/src/subsidy_schedule.rs', lines 24:0-32:1
    Visibility: public -/
structure subsidy_schedule.Subsidy where
  total : Std.U64
  deferred : Std.U64

/-- [hayai_consensus_core::coinbase_value::CoinbaseTerms]
    Source: 'crates/hayai-consensus-core/src/coinbase_value.rs', lines 103:0-122:1
    Visibility: public -/
structure coinbase_value.CoinbaseTerms where
  subsidy : subsidy_schedule.Subsidy
  required : alloc.vec.Vec coinbase_value.RequiredOutput
  disbursed : Std.U64
  exact_value : Bool
  nsm_fee_share : Bool
  miner_subsidy : Std.U64

/-- [hayai_consensus_core::rule_sets::DifficultyParams]
    Source: 'crates/hayai-consensus-core/src/rule_sets.rs', lines 79:0-95:1
    Visibility: public -/
structure rule_sets.DifficultyParams where
  target_spacing : Std.U32
  averaging_window : Std.U32
  max_adjust_up_percent : Std.U32
  max_adjust_down_percent : Std.U32
  damping_factor : Std.U32
  min_difficulty_gap_spacings : Std.U32

/-- [hayai_consensus_core::rule_sets::CoinbaseRules]
    Source: 'crates/hayai-consensus-core/src/rule_sets.rs', lines 62:0-75:1
    Visibility: public -/
structure rule_sets.CoinbaseRules where
  expiry_is_height : Bool
  shielded_outputs : Bool
  exact_value : Bool
  orchard_bundle : Bool
  nsm_fee_share : Bool

/-- [hayai_consensus_core::rule_sets::HistoryVersion]
    Source: 'crates/hayai-consensus-core/src/rule_sets.rs', lines 49:0-58:1
    Visibility: public -/
@[discriminant isize]
inductive rule_sets.HistoryVersion where
| None : rule_sets.HistoryVersion
| V1 : rule_sets.HistoryVersion
| V2 : rule_sets.HistoryVersion
| V3 : rule_sets.HistoryVersion

/-- [hayai_consensus_core::rule_sets::ShieldedPools]
    Source: 'crates/hayai-consensus-core/src/rule_sets.rs', lines 40:0-45:1
    Visibility: public -/
structure rule_sets.ShieldedPools where
  sprout : Bool
  sapling : Bool
  orchard : Bool
  ironwood : Bool

/-- [hayai_consensus_core::rule_sets::TxVersions]
    Source: 'crates/hayai-consensus-core/src/rule_sets.rs', lines 13:0-13:26
    Visibility: public -/
@[reducible]
def rule_sets.TxVersions := Std.U8

/-- [hayai_consensus_core::rule_sets::RuleSet]
    Source: 'crates/hayai-consensus-core/src/rule_sets.rs', lines 136:0-151:1
    Visibility: public -/
structure rule_sets.RuleSet where
  upgrade : chain_spec.Upgrade
  branch_id : Std.U32
  tx_versions : rule_sets.TxVersions
  script_flags : Std.U32
  pools : rule_sets.ShieldedPools
  sprout_deposit : Bool
  limits : block_limits.BlockLimits
  history : rule_sets.HistoryVersion
  coinbase : rule_sets.CoinbaseRules
  difficulty : rule_sets.DifficultyParams

/-- [hayai_consensus_core::funding::FundingStream]
    Source: 'crates/hayai-consensus-core/src/funding.rs', lines 36:0-42:1
    Visibility: public -/
structure funding.FundingStream where
  receiver : funding.Receiver
  value : Std.U64
  script : Option (Array Std.U8 23#usize)

/-- [hayai_consensus_core::founders::FoundersReward]
    Source: 'crates/hayai-consensus-core/src/founders.rs', lines 18:0-23:1
    Visibility: public -/
structure founders.FoundersReward where
  value : Std.U64
  script : Array Std.U8 23#usize

/-- [hayai_consensus_core::difficulty_rules::Uint256]
    Source: 'crates/hayai-consensus-core/src/difficulty_rules.rs', lines 42:0-42:33
    Visibility: public -/
@[reducible]
def difficulty_rules.Uint256 := Array Std.U64 4#usize

/-- [hayai_consensus_core::difficulty_rules::ParentChain]
    Source: 'crates/hayai-consensus-core/src/difficulty_rules.rs', lines 343:0-352:1
    Visibility: public -/
structure difficulty_rules.ParentChain where
  height : Std.U32
  times : Slice Std.U32
  bits : Slice Std.U32

/-- [hayai_consensus_core::difficulty_rules::ContextTooShort]
    Source: 'crates/hayai-consensus-core/src/difficulty_rules.rs', lines 360:0-365:1
    Visibility: public -/
structure difficulty_rules.ContextTooShort where
  times : Std.Usize
  needed_times : Std.Usize
  bits : Std.Usize
  needed_bits : Std.Usize

/-- [hayai_consensus_core::difficulty_rules::DifficultyError]
    Source: 'crates/hayai-consensus-core/src/difficulty_rules.rs', lines 368:0-379:1
    Visibility: public -/
@[discriminant isize]
inductive difficulty_rules.DifficultyError where
| Genesis : difficulty_rules.DifficultyError
| ContextTooShort :
  difficulty_rules.ContextTooShort →
  difficulty_rules.DifficultyError
| Rules : ConsensusError → difficulty_rules.DifficultyError
| InvalidContextBits : Std.U32 → difficulty_rules.DifficultyError

/-- [hayai_consensus_core::difficulty_rules::expected_bits::{closure}]
    Source: 'crates/hayai-consensus-core/src/difficulty_rules.rs', lines 481:16-486:5 -/
def difficulty_rules.expected_bits.closure := Slice Std.U32 × Slice Std.U32

/-- [hayai_consensus_core::header_rules::HeaderFields]
    Source: 'crates/hayai-consensus-core/src/header_rules.rs', lines 41:0-48:1
    Visibility: public -/
structure header_rules.HeaderFields where
  version : Std.U32
  time : Std.U32
  bits : Std.U32

/-- [hayai_consensus_core::header_rules::HeaderError]
    Source: 'crates/hayai-consensus-core/src/header_rules.rs', lines 51:0-72:1
    Visibility: public -/
@[discriminant isize]
inductive header_rules.HeaderError where
| Genesis : header_rules.HeaderError
| Version : Std.U32 → header_rules.HeaderError
| InvalidBits : Std.U32 → header_rules.HeaderError
| TargetAboveLimit : Std.U32 → header_rules.HeaderError
| WrongBits : Std.U32 → Std.U32 → header_rules.HeaderError
| TimeTooEarly : Std.U32 → Std.U32 → header_rules.HeaderError
| TimeTooLate : Std.U32 → Std.U32 → header_rules.HeaderError
| TimeTooFarAhead : Std.U32 → Std.U32 → header_rules.HeaderError
| Rules : ConsensusError → header_rules.HeaderError
| InvalidContextBits : Std.U32 → header_rules.HeaderError

/-- [hayai_consensus_core::header_rules::Unchecked]
    Source: 'crates/hayai-consensus-core/src/header_rules.rs', lines 76:0-84:1
    Visibility: public -/
structure header_rules.Unchecked where
  time : Bool
  bits : Bool
  context : difficulty_rules.ContextTooShort

/-- [hayai_consensus_core::header_rules::HeaderVerdict]
    Source: 'crates/hayai-consensus-core/src/header_rules.rs', lines 89:0-95:1
    Visibility: public -/
@[discriminant isize]
inductive header_rules.HeaderVerdict where
| Checked : header_rules.HeaderVerdict
| ContextTooShort : header_rules.Unchecked → header_rules.HeaderVerdict

end HayaiCore
